### ISSUE TITLE
Recoverable errors when loading section after updating server from V11.5 to V12  in 1.18.2

### ISSUE THREAD

**Issue by DanielDelRincon** [LunaPixelStudios/Better-MC-PLUS#41]
### Describe the Bug

After i updated the world, a message appear in the console saying that "Recoverable errors when loading section [-17, -2, 37]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: warden_and_sculk:sculk_biome -> using default)" multiple times. 

It makes difficult to correctly manage the server and i'm wondering if i did something bad when updating. 

### Reproduction Steps

1. Create a world and play it in V11.5
2. Update the world to V12

### Screenshots and Videos

![2022-07-12 19_12_02](https://user-images.githubusercontent.com/105493500/178552483-2c67d814-2d46-4100-a814-151f08fdff22.png)

### Crash Report or Log

https://gist.github.com/DanielDelRincon/5a00a35d75415c61b07ea33b967303a2

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V12

### Optifine

No

**Comment by SHXRKIIE** [comment]
That mod was removed so it will throw errors, as long their are no crashes it is nothing to worry about
