### ISSUE TITLE
server wont start

### ISSUE THREAD

**Issue by TameEnderman923** [LunaPixelStudios/Better-MC-PLUS#42]
### Describe the Bug

when I double click the .bat file to start the server i get this

forge.jar present. Moving on...
minecraft_server."1.16.5".jar present. Moving on...
User did not agree to Mojang's EULA.
eula.txt present. Moving on...
Starting server...
Minecraft version: "1.16.5"
Forge version: "36.2.35"
Java version:
Java args: "-Xmx5G"

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/TameEnderman923/358587b633808ff3aa6b2959f0144304

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V39.5

### Optifine

No

### Other Mods

no other mods were added

**Comment by SHXRKIIE** [comment]
Your Log doesnt help, I can only assume you have Java 17 installed, uninstall it

**Comment by TameEnderman923** [comment]
i have it running on the latest java 8
