### ISSUE TITLE
server wont start

### ISSUE THREAD

**Issue by TameEnderman923** [LunaPixelStudios/Better-MC-PLUS#43]
### Describe the Bug

I doubled click the .bat file and it goes through a few things but then give me the prompt to press any key to close the window.
I am running java 8 version 331

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/TameEnderman923/5c3b850bbe626b523a5039f60ccf4221

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V39.5

### Optifine

No

### Other Mods

no other mods were added

**Comment by TameEnderman923** [comment]
ok i fixed that part but im getting this issue "incomplete set of tags received from server" when I try to join the server any idea of how to fix this?

**Comment by SHXRKIIE** [comment]
"incomplete set of tags received from server" means the server and client doesnt match
